# Resolução Lista 2

Prof. Daniel de Abreu Pereira Uhr



### 1. Conversão de Tipos

##### 1.1 Carregue o seguinte dicionário como um DataFrame do pandas e verifique os tipos das colunas.


In [7]:
import pandas as pd
dados = {'ID': ['1', '2', '3'], 'Valor': ['10.5', '20.8', '30.2'], 'Data': ['2024-01-01', '2024-02-15', '2024-03-10']}
df = pd.DataFrame(dados)
print(df.dtypes)

ID       object
Valor    object
Data     object
dtype: object


##### 1.2 Converta a coluna 'ID' para inteiro, 'Valor' para float e 'Data' para datetime.

In [8]:
df['ID'] = df['ID'].astype(int)
df['Valor'] = df['Valor'].astype(float)
df['Data'] = pd.to_datetime(df['Data'])
print(df.dtypes)

ID                int32
Valor           float64
Data     datetime64[ns]
dtype: object


### 2. Tratamento de Valores Ausentes

In [9]:
dados = {'A': [1, 2, None, 4], 'B': [None, 5, 6, 7], 'C': [10, None, None, 40]}

df = pd.DataFrame(dados)

df.fillna(df.mean(), inplace=True)

print(df)


          A    B     C
0  1.000000  6.0  10.0
1  2.000000  5.0  25.0
2  2.333333  6.0  25.0
3  4.000000  7.0  40.0


### 3. Manipulação de Strings

##### 3.1 Crie um DataFrame contendo nomes completos e extraia apenas os sobrenomes.

In [ ]:
df = pd.DataFrame({'Nome': ['Ana Silva', 'Bruno Souza', 'Carlos Pereira']})
df['Sobrenome'] = df['Nome'].apply(lambda x: x.split()[-1])
print(df)

### 4. Criação de Novas Colunas

##### 4.1 A partir do DataFrame `df` abaixo, crie uma nova coluna chamada 'Desconto', que seja 10% do valor da coluna 'Valor'.

In [3]:
df = pd.DataFrame({'Produto': ['A', 'B', 'C'], 'Valor': [100, 200, 300]})
df['Desconto'] = df['Valor'] * 0.1
print(df)

  Produto  Valor  Desconto
0       A    100      10.0
1       B    200      20.0
2       C    300      30.0


### 5. Uso do Numpy

##### 5.1 Crie um array NumPy de números aleatórios entre 1 e 100 de tamanho (5,5) e substitua os valores menores que 50 por 0.

In [4]:
import numpy as np
arr = np.random.randint(1, 100, (5,5))
arr[arr < 50] = 0
print(arr)

[[ 0 83  0  0  0]
 [ 0  0  0  0  0]
 [52 85 84 67  0]
 [58  0  0  0 83]
 [ 0 84  0 91 82]]


### 6. Filtragem de Dados

##### 6.1 Usando o seguinte DataFrame, filtre apenas os produtos com valor acima de 150.

In [5]:
df = pd.DataFrame({'Produto': ['A', 'B', 'C', 'D'], 'Valor': [120, 180, 90, 200]})
df_filtrado = df[df['Valor'] > 150]
print(df_filtrado)

  Produto  Valor
1       B    180
3       D    200


```python

```